### ISSUE TITLE
Creative terminal can't fill crafting grid using JEI

### ISSUE THREAD

**Issue by TheThingG** [p455w0rd/WirelessCraftingTerminal#334]
1.12.2-3.11.88
When you out of access point range you can't shift+click on plus in jei recipe window. Resources does'nt appear in crafting grid. This bug appears only when using creative version of terminal.

**Comment by p455w0rd** [comment]
Thank you. I will take your work that this is true and mark it as a bug. I'll do my best to remember to have it fixed in the next update.

**Comment by Milii20** [comment]
Maybe this can help a bit
one curious thing, still happening on 3.12.93, BUT on one condition, if you go far enough from the wireless access point, or you go to another dimension, the creative crafting terminal CANT fill the crafting grid using JEI, but it does work if you are close enough to the access point, needless to say, tried with the normal non creative version, and said version does work even across dimensions

**Comment by p455w0rd** [comment]
Can one of you please join [discord](https://p455w0rd.net/discord) so I can send you a dev jar to test?

**Comment by Milii20** [comment]
On my way!
