### ISSUE TITLE
Crash with TAG_List of TAG_End's is an empty string.

### ISSUE THREAD

**Issue by Zethalion** [p455w0rd/WirelessCraftingTerminal#74]
WirelessCraftingTerminal-1.7.10-rv3-1.8.7.1b
Also reported here: https://github.com/ForgeEssentials/ForgeEssentials/issues/2146

I was told the data structure of the mod is not in order.

**Comment by AnrDaemon** [comment]
To give a clearer understanding of what you are trying to do (and to quote the standard), a TAG_List is

> A list of `tag` payloads, without repeated tag IDs or any tag names.

And since TAG_End is an empty tag consisting solely of tag ID, a TAG_List of TAG_End's of any size will just be an empty string… Which is only theoretically valid. But makes absolutely no sense in practice.

Said all that, please make your mind up on the matter and either store an actual data, or don't try to store nothing and expect everyone to waste time interpreting it.

**Comment by p455w0rd** [comment]
wot?

**Comment by olee** [comment]
Basically it is empty data - it means this list will never be able to contain any data at all.

**Comment by AnrDaemon** [comment]
Oh? interesting.
@p455w0rd , if you can explain, what that structure contains and how it is created, it would be easier to find the origin of the issue.

**Comment by p455w0rd** [comment]
It could be the magnet list, the WCT inventor, or maybe the trash slot? I don't know..That crash report tells me nothing. If someone wants to work with me, I'm totally open to figuring this out. I'm seriously lost. With no crash report to even tell what item in the mod is doing it, I feel like it would be hours spent on a mod that was made for a now obsolete version of the game.

**Comment by AnrDaemon** [comment]
It appears, if you create a TAG_List, but don't populate it, it have the type of TAG_End by default.
This should be fixed on FE side now. Sorry for disturbance.

**Comment by p455w0rd** [comment]
I see...This would lead me to believe it's the magnet inventory. If @olee 's commit ( https://github.com/ForgeEssentials/ForgeEssentials/commit/34ef6a6181873aaca0bf44f083c65ada0c5f8cee ) doesn't fix, then I'll look more into it.
